[env]
TERM = "xterm-256color"
WINIT_X11_SCALE_FACTOR = "1"

[window]
dynamic_padding = true
decorations = "full"
title = "Alacritty"
opacity = 1
decorations_theme_variant = "Dark"

[window.dimensions]
columns = 100
lines = 30

[window.class]
instance = "Alacritty"
general = "Alacritty"

[scrolling]
history = 10000
multiplier = 3

[colors]
draw_bold_text_with_bright_colors = true

[colors.primary]
background = "0x070e15"
foreground = "0xc0caf5"

[colors.normal]
black   = "0x15161e"
red     = "0xf7768e"
green   = "0x9ece6a"
yellow  = "0xe0af68"
blue    = "0x7aa2f7"
magenta = "0xbb9af7"
cyan    = "0x7dcfff"
white   = "0xa9b1d6"

[colors.bright]
black   = "0x414868"
red     = "0xff899d"
green   = "0x9ece6a"
yellow  = "0xfaba4a"
blue    = "0x8db0ff"
magenta = "0xc7a9ff"
cyan    = "0xa4daff"
white   = "0xc0caf5"


# rose pine palette
# [colors.normal]
# black = "0x232136"
# red = "0xEB6F92"
# green = "0x3E8FB0"
# yellow = "0xF6C177"
# blue = "0x9CCFD8"
# magenta = "0xC4A7E7"
# cyan = "0xEA9A97"
# white = "0xE0DEF4"
#
# [colors.bright]
# black = "0x393552"
# red = "0xEB6F92"
# green = "0x3E8FB0"
# yellow = "0xF6C177"
# blue = "0x9CCFD8"
# magenta = "0xC4A7E7"
# cyan = "0xEBBCBA"
# white = "0xE0DEF4"
#
[font]
size = 20

[font.normal]
family = "monospace"
style = "Regular"

[font.bold]
family = "monospace"
style = "Bold"

[font.italic]
family = "monospace"
style = "Italic"

[font.bold_italic]
family = "monospace"
style = "Bold Italic"

[selection]
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"
save_to_clipboard = true

[cursor]
style = "block"
vi_mode_style = "None"
unfocused_hollow = true
thickness = 0.15

[mouse]
hide_when_typing = true

[[mouse.bindings]]
mouse = "Middle"
action = "PasteSelection"

[keyboard]
[[keyboard.bindings]]
key = "Paste"
action = "Paste"

[[keyboard.bindings]]
key = "Copy"
action = "Copy"

[[keyboard.bindings]]
key = "L"
mods = "Control"
action = "ClearLogNotice"

[[keyboard.bindings]]
key = "L"
mods = "Control"
mode = "~Vi"
chars = "\f"

[[keyboard.bindings]]
key = "PageUp"
mods = "Shift"
mode = "~Alt"
action = "ScrollPageUp"

[[keyboard.bindings]]
key = "PageDown"
mods = "Shift"
mode = "~Alt"
action = "ScrollPageDown"

[[keyboard.bindings]]
key = "Home"
mods = "Shift"
mode = "~Alt"
action = "ScrollToTop"

[[keyboard.bindings]]
key = "End"
mods = "Shift"
mode = "~Alt"
action = "ScrollToBottom"

[[keyboard.bindings]]
key = "V"
mods = "Control|Shift"
action = "Paste"

[[keyboard.bindings]]
key = "C"
mods = "Control|Shift"
action = "Copy"

[[keyboard.bindings]]
key = "F"
mods = "Control|Shift"
action = "SearchForward"

[[keyboard.bindings]]
key = "B"
mods = "Control|Shift"
action = "SearchBackward"

[[keyboard.bindings]]
key = "C"
mods = "Control|Shift"
mode = "Vi"
action = "ClearSelection"

[[keyboard.bindings]]
key = "Key0"
mods = "Control"
action = "ResetFontSize"

[general]
live_config_reload = true
working_directory = "None"

[[keyboard.bindings]]
key = "H"
mods = "Super"
chars = "\u001Bh"

[[keyboard.bindings]]
key = "L"
mods = "Super"
chars = "\u001Bl"
