[cursor.style]
blinking = "Off"
shape = "Block"

[selection]
save_to_clipboard = true

[window]
decorations = "none"
dynamic_title = true
opacity = 1
dynamic_padding = true

[window.padding]
x = 5
y = 5

[scrolling]
history = 10000
multiplier = 3

[bell]
animation = "Linear"
duration = 0
command = { program = "paplay", args = [
  "/usr/share/sounds/freedesktop/stereo/dialog-error.oga",
] }

[colors.primary]
background="#000000"

[general]
live_config_reload = true

import = [
  "~/.config/alacritty/fonts.toml",
]
