#!/bin/sh
HISTFILE="$XDG_DATA_HOME"/zsh/history
HISTSIZE=1000000
SAVEHIST=1000000
export PATH="$HOME/.local/bin":$PATH
export MANPAGER='nvim +Man!'
export MANWIDTH=999
export BROWSER='firefox'
export EDITOR="nvim"
export VISUAL="$EDITOR"
export PATH=$HOME/.cargo/bin:$PATH
export PATH=$HOME/.local/share/go/bin:$PATH
export GOPATH=$HOME/.local/share/go
export FPATH="$HOME/eza/completions/zsh:$FPATH"
export PATH="$HOME/.local/bin:$HOME/bin:/usr/local/bin:$GOPATH/bin:$PATH"
export PATH=$HOME/.miniconda/bin:$PATH
export SUDO_PROMPT="Deploying root access for %u. Enter Password : "
# fnm
if command -v fnm >/dev/null; then
  eval "$(fnm env --use-on-cd --shell zsh)"
fi
#atuin
if command -v atuin >/dev/null; then
  eval "$(atuin init zsh)"
fi
# zoxide
if command -v zoxide >/dev/null; then
  eval "$(zoxide init zsh)"
fi

# krabby splash
[[ $- == *i* ]] && command -v krabby &>/dev/null && krabby random

. "$HOME/.atuin/bin/env"
