#!/bin/sh

## autoload vcs and colors
autoload -Uz vcs_info
autoload -U colors && colors

# enable only git 
zstyle ':vcs_info:*' enable git 

# setup a hook that runs before every prompt
precmd_vcs_info() { vcs_info }
precmd_functions+=( precmd_vcs_info )
setopt prompt_subst

# add a function to check for untracked files in the directory
zstyle ':vcs_info:git*+set-message:*' hooks git-untracked
+vi-git-untracked() {
    if [[ $(git rev-parse --is-inside-work-tree 2> /dev/null) == 'true' ]] && \
        git status --porcelain | grep '??' &> /dev/null ; then
        hook_com[staged]+='!' # signify new files with a bang
    fi
}

zstyle ':vcs_info:*' check-for-changes true
zstyle ':vcs_info:git:*' stagedstr '+'
zstyle ':vcs_info:git:*' unstagedstr '*'
zstyle ':vcs_info:git:*' formats " %{$fg[blue]%}(%{$fg[red]%}%m%{$fg[yellow]%}%u%{$fg[green]%}%c%{$fg[magenta]%}%{$fg[red]%} %b%{$fg[blue]%})"
zstyle ':vcs_info:git:*' actionformats " %{$fg[blue]%}(%{$fg[red]%}%a %b%{$fg[blue]%})"

# --- Prompt format ---
# username@hostname current_directory git_info$
PROMPT="%{$fg[blue]%}%n%{$reset_color%}@%{$fg[blue]%}%m%{$reset_color%} "
PROMPT+="%{$fg[cyan]%}%~%{$reset_color%} "
PROMPT+="\$vcs_info_msg_0_"
PROMPT+="%{$fg[white]%}$ %{$reset_color%}"
