-- Background Autostarts
hl.on("hyprland.start", function()
        hl.exec_cmd("hyprpaper &")
        hl.exec_cmd("nm-applet &")
        hl.exec_cmd("waybar &")
        hl.exec_cmd("cliphist daemon")
        hl.exec_cmd("blueman-applet")
        hl.exec_cmd("/home/prakhar/.local/bin/battery-notify.sh")
        hl.exec_cmd("mako &")
        hl.exec_cmd("wl-paste --type text --watch cliphist store")
        hl.exec_cmd("wl-paste --type image --watch cliphist store")
end)
