exec = gsettings set org.gnome.desktop.interface gtk-theme 'Wallbash-Gtk'
exec = gsettings set org.gnome.desktop.interface color-scheme 'prefer-dark'

general {
    col.active_border = rgba(DADBD8ff) rgba(1A1A1Aff) 45deg
    col.inactive_border = rgba(0F0F0Fff) rgba(323233ff) 45deg
}

group {
    col.border_active = rgba(DADBD8ff) rgba(1A1A1Aff) 45deg
    col.border_inactive = rgba(0F0F0Fcc) rgba(323233cc) 45deg
    col.border_locked_active = rgba(141414ff) rgba(060606ff) 45deg
    col.border_locked_inactive = rgba(FFFFFFcc) rgba(FFFFFFcc) 45deg
}
