exec = gsettings set org.gnome.desktop.interface gtk-theme 'Wallbash-Gtk'
exec = gsettings set org.gnome.desktop.interface color-scheme 'prefer-dark'

general {
    col.active_border = rgba(747397ff) rgba(2A2952ff) 45deg
    col.inactive_border = rgba(16171Dff) rgba(222435ff) 45deg
}

group {
    col.border_active = rgba(747397ff) rgba(2A2952ff) 45deg
    col.border_inactive = rgba(16171Dcc) rgba(222435cc) 45deg
    col.border_locked_active = rgba(FFFFFFff) rgba(E6E6E5ff) 45deg
    col.border_locked_inactive = rgba(FFFFFFcc) rgba(FFFFFFcc) 45deg
}
