exec = gsettings set org.gnome.desktop.interface gtk-theme 'Wallbash-Gtk'
exec = gsettings set org.gnome.desktop.interface color-scheme 'prefer-dark'

general {
    col.active_border = rgba(C89F8Aff) rgba(523729ff) 45deg
    col.inactive_border = rgba(223439ff) rgba(3D968Cff) 45deg
}

group {
    col.border_active = rgba(C89F8Aff) rgba(523729ff) 45deg
    col.border_inactive = rgba(223439cc) rgba(3D968Ccc) 45deg
    col.border_locked_active = rgba(FFFFFFff) rgba(0D0E0Eff) 45deg
    col.border_locked_inactive = rgba(FFFFFFcc) rgba(191717cc) 45deg
}
