#!/usr/bin/env bash
## Copyright (C) 2020-2024 Aditya Shakya
##

# Run ncmpcpp with alternate config in kitty terminal

# bspwm directory
DIR="$HOME/.config/bspwm"
CONFIG="$DIR/kitty/kitty.conf"

kitty --class Music --config "$CONFIG" \
  --override font_size=12 \
  --override initial_window_width=80c \
  --override initial_window_height=20c \
  bash -c "~/.ncmpcpp/scripts/ncmpcpp-art"
