#!/usr/bin/env bash

## Copyright (C) 2020-2024 Aditya Shakya <adi1090x@gmail.com>
##
## launch kitty with bspwm config and background opacity

# bspwm directory
DIR="$HOME/.config/bspwm"
CONFIG="$DIR/kitty/kitty.conf"

if [ "$1" == "--float" ]; then
  kitty --class kitty-float --config "$CONFIG"
elif [ "$1" == "--full" ]; then
  kitty --class kitty-fullscreen --config "$CONFIG" --start-as fullscreen
else
  kitty --config "$CONFIG" ${@}
fi
