# New hyprpaper configuration block format
wallpaper {
        monitor = eDP-2
        path = /home/pp/current_wallpaper.png
        fit_mode = cover
}
 wallpaper {
monitor = eDP-1
        path = /home/pp/current_wallpaper.png
        fit_mode = cover
}

ipc = true
splash = false
