"$schema" = "https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json"
console_title_template = '{{ .Shell }} in {{ .Folder }}'
version = 3
final_space = true

[[blocks]]
    type='prompt'
    alignment='left'
    newline=true

    [[blocks.segments]]
        type='path'
        style='plain'
        background='transparent'
        foreground='#8897F4'
        template='{{ .Path }}'
        
        [blocks.segments.properties]
            style='full'

    [[blocks.segments]]
        # type = 'git'
        # style = 'plain'
        template = '<#5FAAE8> 󰊤 git:(</>{{ .HEAD }}{{ if or (.Working.Changed) (.Staging.Changed) }} *{{ end }}<cyan>{{ if gt .Behind 0 }} ⇣{{ end }}{{ if gt .Ahead 0 }} ⇡{{ end }}<#5FAAE8>)</>'
        # foreground = '#6c6c6c'
        # background = 'transparent'
        foreground = "#D0666F"
        style = "plain"
        type = "git"
        [blocks.segments.properties]
            branch_icon=''
            commit_icon = '@'
            fetch_status=true

[[blocks]]
    type='prompt'
    alignment='left'
    newline=true

    [[blocks.segments]]
        type='text'
        style='plain'
        foreground_templates = ['{{if gt .Code 0}}red{{end}}', '{{if eq .Code 0}}#C574DD{{end}}']
        background='transparent'
        # foreground='#C574DD'
        template = "➜"
[transient_prompt]
    # foreground="#C574DD"
    foreground_templates = ['{{if gt .Code 0}}red{{end}}', '{{if eq .Code 0}}#C574DD{{end}}']
    background='transparent'
    # template="❯ " 
    template = "➜ "


[secondary_prompt]
  template = '❯❯ '
  foreground = '#C574DD'
  background = 'transparent'


