  	## Colors configuration
  	[colors.primary]
  	background = "#1E2128"
  	foreground = "#ABB2BF"

  	[colors.normal]
  	black   = "#32363D"
  	red     = "#E06B74"
  	green   = "#98C379"
  	yellow  = "#E5C07A"
  	blue    = "#62AEEF"
  	magenta = "#C778DD"
  	cyan    = "#55B6C2"
  	white   = "#ABB2BF"

  	[colors.bright]
  	black   = "#50545B"
  	red     = "#EA757E"
  	green   = "#A2CD83"
  	yellow  = "#EFCA84"
  	blue    = "#6CB8F9"
  	magenta = "#D282E7"
  	cyan    = "#5FC0CC"
  	white   = "#B5BCC9"
  _EOF_

  # xfce terminal : fonts & colors
  xfconf-query -c xfce4-terminal -p /font-name -s "Cascadia Mono NF 10"
  xfconf-query -c xfce4-terminal -p /color-background -s "#1E2128"
  xfconf-query -c xfce4-terminal -p /color-foreground -s "#ABB2BF"
  xfconf-query -c xfce4-terminal -p /color-cursor -s "#ABB2BF"
  xfconf-query -c xfce4-terminal -p /color-palette -s "#32363D;#E06B74;#98C379;#E5C07A;#62AEEF;#C778DD;#55B6C2;#ABB2BF;#50545B;#EA757E;#A2CD83;#EFCA84;#6CB8F9;#D282E7;#5FC0CC;#B5BCC9"
}
apply_kitty() {
  # Kitty: Fonts
  kitty conf --load kitty.conf -o shell_always_use_gpu=false -o font="Cascadia Mono NF" -o font_size="10"

  # Kitty: Colors (using kitty config file)
  cat <<EOF >>kitty.conf
  [colors]
    background = "#1E2128"
    foreground = "#ABB2BF"

  [colors.bright_foreground]
    black = "#50545B"
    red = "#EA757E"
    green = "#A2CD83"
    yellow = "#EFCA84"
    blue = "#6CB8F9"
    magenta = "#D282E7"
    cyan = "#5FC0CC"
    white = "#B5BCC9"

  [colors.bright_background]
    black = ""
    red = ""
    green = ""
    yellow = ""
    blue = ""
    magenta = ""
    cyan = ""
    white = ""

  [colors.ansi_palette]
    0 = "#32363D"
    1 = "#E06B74"
    2 = "#98C379"
    3 = "#E5C07A"
    4 = "#62AEEF"
    5 = "#C778DD"
    6 = "#55B6C2"
    7 = "#ABB2BF"
    8 = "#50545B"
    9 = "#EA757E"
    10 = "#A2CD83"
    11 = "#EFCA84"
    12 = "#6CB8F9"
    13 = "#D282E7"
    14 = "#5FC0CC"
    15 = "#B5BCC9"
EOF

  # Reload kitty configuration
  kitty conf --reload kitty.conf
}

# Geany -------------------------------------
apply_geany() {
  sed -i /home/prakhar/.config/geany/geany.conf     -e "s/color_scheme=.*/color_scheme=arc.conf/g"     -e "s/editor_font=.*/editor_font=Cascadia Mono 10/g"
}

# Appearance --------------------------------
apply_appearance() {
  # apply gtk theme, icons, cursor & fonts
  xfconf-query -c xsettings -p /Gtk/FontName -s "Cascadia Monoo"
  xfconf-query -c xsettings -p /Net/ThemeName -s "Blade"
  xfconf-query -c xsettings -p /Net/IconThemeName -s "Win11-Dark"
  xfconf-query -c xsettings -p /Gtk/CursorThemeName -s "Qogirr"

  # inherit cursor theme
  if [[ -f "/home/prakhar"/.icons/default/index.theme ]]; then
    sed -i -e "s/Inherits=.*/Inherits=Qogirr/g" "/home/prakhar"/.icons/default/index.theme
  fi
}

# Openbox -----------------------------------
apply_obconfig() {
  namespace="http://openbox.org/3.4/rc"
  config="/home/prakhar/.config/openbox/rc.xml"

  # Theme
  xmlstarlet ed -L -N a="" -u '/a:openbox_config/a:theme/a:name' -v "Catppuccin-Mocha" ""

  # Title
  xmlstarlet ed -L -N a="" -u '/a:openbox_config/a:theme/a:titleLayout' -v "DLSIMC" ""

  # Fonts
  xmlstarlet ed -L -N a="" -u '/a:openbox_config/a:theme/a:font[@place="ActiveWindow"]/a:name' -v "Cascadia Mono" ""
  xmlstarlet ed -L -N a="" -u '/a:openbox_config/a:theme/a:font[@place="ActiveWindow"]/a:size' -v "10" ""
  xmlstarlet ed -L -N a="" -u '/a:openbox_config/a:theme/a:font[@place="ActiveWindow"]/a:weight' -v Bold ""
  xmlstarlet ed -L -N a="" -u '/a:openbox_config/a:theme/a:font[@place="ActiveWindow"]/a:slant' -v Normal ""

  xmlstarlet ed -L -N a="" -u '/a:openbox_config/a:theme/a:font[@place="InactiveWindow"]/a:name' -v "Cascadia Mono" ""
  xmlstarlet ed -L -N a="" -u '/a:openbox_config/a:theme/a:font[@place="InactiveWindow"]/a:size' -v "10" ""
  xmlstarlet ed -L -N a="" -u '/a:openbox_config/a:theme/a:font[@place="InactiveWindow"]/a:weight' -v Normal ""
  xmlstarlet ed -L -N a="" -u '/a:openbox_config/a:theme/a:font[@place="InactiveWindow"]/a:slant' -v Normal ""

  xmlstarlet ed -L -N a="" -u '/a:openbox_config/a:theme/a:font[@place="MenuHeader"]/a:name' -v "Cascadia Mono" ""
  xmlstarlet ed -L -N a="" -u '/a:openbox_config/a:theme/a:font[@place="MenuHeader"]/a:size' -v "10" ""
  xmlstarlet ed -L -N a="" -u '/a:openbox_config/a:theme/a:font[@place="MenuHeader"]/a:weight' -v Bold ""
  xmlstarlet ed -L -N a="" -u '/a:openbox_config/a:theme/a:font[@place="MenuHeader"]/a:slant' -v Normal ""

  xmlstarlet ed -L -N a="" -u '/a:openbox_config/a:theme/a:font[@place="MenuItem"]/a:name' -v "Cascadia Mono" ""
  xmlstarlet ed -L -N a="" -u '/a:openbox_config/a:theme/a:font[@place="MenuItem"]/a:size' -v "10" ""
  xmlstarlet ed -L -N a="" -u '/a:openbox_config/a:theme/a:font[@place="MenuItem"]/a:weight' -v Normal ""
  xmlstarlet ed -L -N a="" -u '/a:openbox_config/a:theme/a:font[@place="MenuItem"]/a:slant' -v Normal ""

  xmlstarlet ed -L -N a="" -u '/a:openbox_config/a:theme/a:font[@place="ActiveOnScreenDisplay"]/a:name' -v "Cascadia Mono" ""
  xmlstarlet ed -L -N a="" -u '/a:openbox_config/a:theme/a:font[@place="ActiveOnScreenDisplay"]/a:size' -v "10" ""
  xmlstarlet ed -L -N a="" -u '/a:openbox_config/a:theme/a:font[@place="ActiveOnScreenDisplay"]/a:weight' -v Bold ""
  xmlstarlet ed -L -N a="" -u '/a:openbox_config/a:theme/a:font[@place="ActiveOnScreenDisplay"]/a:slant' -v Normal ""

  xmlstarlet ed -L -N a="" -u '/a:openbox_config/a:theme/a:font[@place="InactiveOnScreenDisplay"]/a:name' -v "Cascadia Mono" ""
  xmlstarlet ed -L -N a="" -u '/a:openbox_config/a:theme/a:font[@place="InactiveOnScreenDisplay"]/a:size' -v "10" ""
  xmlstarlet ed -L -N a="" -u '/a:openbox_config/a:theme/a:font[@place="InactiveOnScreenDisplay"]/a:weight' -v Normal ""
  xmlstarlet ed -L -N a="" -u '/a:openbox_config/a:theme/a:font[@place="InactiveOnScreenDisplay"]/a:slant' -v Normal ""

  # Openbox Menu Style
  xmlstarlet ed -L -N a="" -u '/a:openbox_config/a:menu/a:file' -v "menu-icons.xml" ""

  # Margins
  xmlstarlet ed -L -N a="" -u '/a:openbox_config/a:margins/a:top' -v 48 ""
  xmlstarlet ed -L -N a="" -u '/a:openbox_config/a:margins/a:bottom' -v 10 ""
  xmlstarlet ed -L -N a="" -u '/a:openbox_config/a:margins/a:left' -v 10 ""
  xmlstarlet ed -L -N a="" -u '/a:openbox_config/a:margins/a:right' -v 10 ""

  # Reload Openbox Config
  openbox --reconfigure
}

# Dunst -------------------------------------
apply_dunst() {
  # modify dunst config
  sed -i /home/prakhar/.config/dunst/dunstrc     -e "s/width = .*/width = 300/g"     -e "s/height = .*/height = 80/g"     -e "s/offset = .*/offset = 10x48/g"     -e "s/origin = .*/origin = top-right/g"     -e "s/font = .*/font = Cascadia Mono 10/g"     -e "s/frame_width = .*/frame_width = 4/g"     -e "s/separator_height = .*/separator_height = 2/g"     -e "s/line_height = .*/line_height = 2/g"

  # modify colors
  sed -i '/urgency_low/Q' /home/prakhar/.config/dunst/dunstrc
  cat >>/home/prakhar/.config/dunst/dunstrc <<-_EOF_
[urgency_low]
timeout = 2
background = "#1E2128"
foreground = "#ABB2BF"
frame_color = "#292d37"

[urgency_normal]
timeout = 5
background = "#1E2128"
foreground = "#ABB2BF"
frame_color = "#292d37"

[urgency_critical]
timeout = 0
background = "#1E2128"
foreground = "#E06B74"
frame_color = "#E06B74"
